language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

env:
  - DOCTRINE_ORM_VERSION=2.1.*
  - DOCTRINE_ORM_VERSION=2.2.*
  - DOCTRINE_ORM_VERSION=2.3.*
  - DOCTRINE_ORM_VERSION=dev-master

services: mongodb

before_script:
  - pecl -q install mongo-1.3.4 && echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer require doctrine/orm:${DOCTRINE_ORM_VERSION} --dev --no-update
  - composer install --dev